config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  post "/subscribe" => "push_notification_tokens#create"
  get 'admin', to: "admin/questions#index", as: :admin_home
  get '/verification/:token', to: "users#verification", as: :account_activation
  get '/password_resets/:token', to: "password_resets#new", as: :reset_password
  get '/ask_bot', to: "bots#talk"
  get '/bot_response', to: "bots#bot_response"
  resources :password_requests, only: [:create, :new]
  resources :password_resets, only: [:create]

  namespace :admin do
    resources :users, only: [:index, :show] do
      member do
        post 'enable'
        post 'disable'
      end
    end
    resources :answers, only: :index do
      member do
        post 'publish'
        post 'unpublish'
      end
    end
    resources :comments, only: :index do
      member do
        post 'publish'
        post 'unpublish'
      end
    end
    resources :questions, only: [:index, :show] do
      member do
        post 'publish'
        post 'unpublish'
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :topics, only: :show
    get '/my_feed', to: "feeds#my_feed", as: :feed
  end

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      post 'follow'
      post 'unfollow'
    end
  end

  scope :my_account do
    resources :credit_transactions, only: [:index]
    get '/questions', to: "users#myquestions", as: :myquestions
  end

  resources :questions do
    collection do
      post 'new_question_loader'
      get 'following_people_questions'
    end
    member do
      get 'publish', to: "questions#publish", as: :publish
      get 'unpublish', to: "questions#unpublish", as: :unpublish
    end
    resources :answers do
      member do
        get 'upvote', to: "answers#upvote", as: :upvote
        get 'downvote', to: "answers#downvote", as: :downvote
      end
    end
  end

  resources :abuse_reports

  resources :comments, only: [:new, :create] do
    member do
      get 'upvote'
      get 'downvote'
    end
  end

  resources :credits, only: [:new, :create] do
    resources :charges, only: [:new, :create]
  end

  resources :topics, only: [] do
    member do
      get 'questions'
    end
  end

  resources :user_notifications, only: [] do
    collection do
      post 'mark_read'
    end
  end

  controller :search do
    get 'search', action: :create
  end

  controller :session do
    get  'login', action: :new
    post 'login', action: :create
    delete 'logout',action: :destroy
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

	def new
	end

	def create
    user = User.find_by(email: params[:email])
    
    if user && user.authenticate(params[:password]) && user.verified?
      session[:user_id] = user.id
      flash[:notice] = "You have been successfully logged in"
      redirect_to root_path 
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end

  end

  def destroy
    reset_session
    flash[:notice] = "You have been successfully logged out"
    redirect_to root_path
  end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.erb
  <%= form_tag(login_path, method: :post, class: "form-horizontal") do %>
    <fieldset>
    <legend>Please Log In</legend>
      
    <div class="form-group">
      <%= label_tag :email, 'Email:', class: "col-md-2 control-label" %>
      <div class="col-md-8">
        <%= text_field_tag :email, params[:email], class: "form-control", placeholder: "Email" %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :password, 'Password:', class: "col-md-2 control-label" %>
      <div class="col-md-8">
        <%= password_field_tag :password, params[:password], class: "form-control", placeholder: "Password" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-8 col-md-offset-5">
        <%= submit_tag "Login", class: "btn btn-default btn-primary" %>
      </div>
    </div>

    </fieldset>
  <% end %>