config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  post "/subscribe" => "push_notification_tokens#create"
  get 'admin', to: "admin/questions#index", as: :admin_home
  get '/verification/:token', to: "users#verification", as: :account_activation
  get '/password_resets/:token', to: "password_resets#new", as: :reset_password
  get '/ask_bot', to: "bots#talk"
  get '/bot_response', to: "bots#bot_response"
  resources :password_requests, only: [:create, :new]
  resources :password_resets, only: [:create]

  namespace :admin do
    resources :users, only: [:index, :show] do
      member do
        post 'enable'
        post 'disable'
      end
    end
    resources :answers, only: :index do
      member do
        post 'publish'
        post 'unpublish'
      end
    end
    resources :comments, only: :index do
      member do
        post 'publish'
        post 'unpublish'
      end
    end
    resources :questions, only: [:index, :show] do
      member do
        post 'publish'
        post 'unpublish'
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :topics, only: :show
    get '/my_feed', to: "feeds#my_feed", as: :feed
  end

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      post 'follow'
      post 'unfollow'
    end
  end

  scope :my_account do
    resources :credit_transactions, only: [:index]
    get '/questions', to: "users#myquestions", as: :myquestions
  end

  resources :questions do
    collection do
      post 'new_question_loader'
      get 'following_people_questions'
    end
    member do
      get 'publish', to: "questions#publish", as: :publish
      get 'unpublish', to: "questions#unpublish", as: :unpublish
    end
    resources :answers do
      member do
        get 'upvote', to: "answers#upvote", as: :upvote
        get 'downvote', to: "answers#downvote", as: :downvote
      end
    end
  end

  resources :abuse_reports

  resources :comments, only: [:new, :create] do
    member do
      get 'upvote'
      get 'downvote'
    end
  end

  resources :credits, only: [:new, :create] do
    resources :charges, only: [:new, :create]
  end

  resources :topics, only: [] do
    member do
      get 'questions'
    end
  end

  resources :user_notifications, only: [] do
    collection do
      post 'mark_read'
    end
  end

  controller :search do
    get 'search', action: :create
  end

  controller :session do
    get  'login', action: :new
    post 'login', action: :create
    delete 'logout',action: :destroy
  end

end

app/views/user_notifier/email_verification.html.erb
<h1>User Verification Mail</h1>

<p>
  Dear <%= @user.first_name %>,

  Welcome to prashna
  </br>
  Please verify you email by clicking on the link below: 
  <br />
  <%=link_to account_activation_url(@user.verification_token), account_activation_url(@user.verification_token)  %>
</p>
<p>
	This validation link is valid till <%= @user.verification_token_expiry_at %>.
</p>

app/views/user_notifier/new_answer_posted.html.erb
<h1>New answer posted</h1>

<p>
  Dear <%= @user.first_name %>,

  Welcome to prashna
  </br>
  A new answer has been posted to the question <%=link_to question_url(@answer.question), question_url(@answer.question)  %>
</p>

app/views/user_notifier/password_reset.html.erb
<h1>User Verification Mail</h1>

<p>
  Dear <%= @user.first_name %>,

  Welcome to prashna
  </br>
  Please click on the link below to reset your password: 
  <br />
  <%=link_to reset_password_url(@user.forgot_password_token), reset_password_url(@user.forgot_password_token)  %>
  <br />
	This validation link is valid till <%= @user.forgot_password_token_expiry_at %>.
</p>

app/views/user_notifier/user_verification.html.erb
<h1>User Verification Mail</h1>

<p>
  Dear <%= @user.first_name %>,

  Welcome to prashna
  </br>
  Please verify you email by clicking on the link below: 
  <br />
  <%=link_to account_activation_url(@user.verification_token), account_activation_url(@user.verification_token)  %>
</p>