config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  post "/subscribe" => "push_notification_tokens#create"
  get 'admin', to: "admin/questions#index", as: :admin_home
  get '/verification/:token', to: "users#verification", as: :account_activation
  get '/password_resets/:token', to: "password_resets#new", as: :reset_password
  get '/ask_bot', to: "bots#talk"
  get '/bot_response', to: "bots#bot_response"
  resources :password_requests, only: [:create, :new]
  resources :password_resets, only: [:create]

  namespace :admin do
    resources :users, only: [:index, :show] do
      member do
        post 'enable'
        post 'disable'
      end
    end
    resources :answers, only: :index do
      member do
        post 'publish'
        post 'unpublish'
      end
    end
    resources :comments, only: :index do
      member do
        post 'publish'
        post 'unpublish'
      end
    end
    resources :questions, only: [:index, :show] do
      member do
        post 'publish'
        post 'unpublish'
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :topics, only: :show
    get '/my_feed', to: "feeds#my_feed", as: :feed
  end

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      post 'follow'
      post 'unfollow'
    end
  end

  scope :my_account do
    resources :credit_transactions, only: [:index]
    get '/questions', to: "users#myquestions", as: :myquestions
  end

  resources :questions do
    collection do
      post 'new_question_loader'
      get 'following_people_questions'
    end
    member do
      get 'publish', to: "questions#publish", as: :publish
      get 'unpublish', to: "questions#unpublish", as: :unpublish
    end
    resources :answers do
      member do
        get 'upvote', to: "answers#upvote", as: :upvote
        get 'downvote', to: "answers#downvote", as: :downvote
      end
    end
  end

  resources :abuse_reports

  resources :comments, only: [:new, :create] do
    member do
      get 'upvote'
      get 'downvote'
    end
  end

  resources :credits, only: [:new, :create] do
    resources :charges, only: [:new, :create]
  end

  resources :topics, only: [] do
    member do
      get 'questions'
    end
  end

  resources :user_notifications, only: [] do
    collection do
      post 'mark_read'
    end
  end

  controller :search do
    get 'search', action: :create
  end

  controller :session do
    get  'login', action: :new
    post 'login', action: :create
    delete 'logout',action: :destroy
  end

end

app/models/credit.rb
# == Schema Information
#
# Table name: credits
#
#  id         :integer          not null, primary key
#  points     :integer          not null
#  price      :decimal(10, )    not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Credit < ActiveRecord::Base
	validates :points, :price, presence: true
	validates :points, :price,  numericality: {greater_than_or_equal_to: 0.01}

end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  
  before_action :authenticate, only: [:new, :show]
  
  def new
    @credits = Credit.all
  end

end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/_credit.html.erb
<div class="item  col-xs-4 col-lg-4">
    <div class="thumbnail">
        <%=image_tag("dollar.jpeg", alt: "Buy Credits", class: "group list-group-image")%>
        <div class="caption">
            <h4 class="group inner list-group-item-heading">
            <%=credit.points%> CREDITS</h4>
            <p class="group inner list-group-item-text">
            Now you can buy <strong><%=credit.price%> credits</strong> for just <strong>$ <%=credit.price%>.</strong> Click Buy Now to add credits to your wallet.</p>
            <div class="row">
                <div class="col-xs-12 col-md-6">
                    <p class="lead">
                    <%=number_to_currency( credit.price )%></p>
                </div>
                <div class="col-xs-12 col-md-6">
                    <%= link_to "Buy Now", new_credit_charge_path(credit), class: "btn btn-success"%>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/credits/new.html.erb
<h2 class="text-center"><strong>Available Credit Packs</strong></h2>
<div class="container">
<div id="products" class="row list-group">
<%=render @credits%>
</div>
</div>