config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  post "/subscribe" => "push_notification_tokens#create"
  get 'admin', to: "admin/questions#index", as: :admin_home
  get '/verification/:token', to: "users#verification", as: :account_activation
  get '/password_resets/:token', to: "password_resets#new", as: :reset_password
  get '/ask_bot', to: "bots#talk"
  get '/bot_response', to: "bots#bot_response"
  resources :password_requests, only: [:create, :new]
  resources :password_resets, only: [:create]

  namespace :admin do
    resources :users, only: [:index, :show] do
      member do
        post 'enable'
        post 'disable'
      end
    end
    resources :answers, only: :index do
      member do
        post 'publish'
        post 'unpublish'
      end
    end
    resources :comments, only: :index do
      member do
        post 'publish'
        post 'unpublish'
      end
    end
    resources :questions, only: [:index, :show] do
      member do
        post 'publish'
        post 'unpublish'
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :topics, only: :show
    get '/my_feed', to: "feeds#my_feed", as: :feed
  end

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      post 'follow'
      post 'unfollow'
    end
  end

  scope :my_account do
    resources :credit_transactions, only: [:index]
    get '/questions', to: "users#myquestions", as: :myquestions
  end

  resources :questions do
    collection do
      post 'new_question_loader'
      get 'following_people_questions'
    end
    member do
      get 'publish', to: "questions#publish", as: :publish
      get 'unpublish', to: "questions#unpublish", as: :unpublish
    end
    resources :answers do
      member do
        get 'upvote', to: "answers#upvote", as: :upvote
        get 'downvote', to: "answers#downvote", as: :downvote
      end
    end
  end

  resources :abuse_reports

  resources :comments, only: [:new, :create] do
    member do
      get 'upvote'
      get 'downvote'
    end
  end

  resources :credits, only: [:new, :create] do
    resources :charges, only: [:new, :create]
  end

  resources :topics, only: [] do
    member do
      get 'questions'
    end
  end

  resources :user_notifications, only: [] do
    collection do
      post 'mark_read'
    end
  end

  controller :search do
    get 'search', action: :create
  end

  controller :session do
    get  'login', action: :new
    post 'login', action: :create
    delete 'logout',action: :destroy
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_action :authenticate
  before_action :set_credit
  layout 'application'

  def new
  end

  def create
    @order = current_user.orders.pending.build(price: @credit.price, credit_points: @credit.points )

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @credit.price * 100,
      :description => "#{@credit.price} charged for buying credit pack",
      :currency    => 'usd'
    )

    if charge
      @transaction = @order.transactions.build(get_transaction_params(charge))
      @transaction.user = current_user
      @order.status = :processed
      if !@order.save
        Stripe::Refund.create(
          charge: charge.id
        )
      end
    end

  rescue Exception => e
    flash[:error] = e.message
    redirect_to new_credit_charge_path

  end

  private

  def set_credit
    @credit = Credit.find_by(id: params[:credit_id])
    if @credit.nil?
      redirect_to root_path, notice: "No such credit pack exist"
    end
  end

  def get_transaction_params(charge)
    transaction_params = {}
    transaction_params[:charge_id] = charge.id
    transaction_params[:stripe_token] = params[:stripeToken]
    transaction_params[:amount] = charge.amount
    transaction_params[:currency] = charge.currency
    transaction_params[:stripe_customer_id] = charge.customer
    transaction_params[:description] = charge.description
    transaction_params[:stripe_email] = params[:stripeEmail]
    transaction_params[:stripe_token_type] = params[:stripeTokenType]
    transaction_params
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<% if (@order.new_record?) %>
  <%= @order.errors.full_messages%>
  <h2>Sorry, your order could not be processed and a refund for <%= number_to_currency(@credit.price) %> has been initiated</h2>
<% else %>
  <h2>Thanks, you paid <strong><%=number_to_currency(@credit.price)%></strong>! for your purchase of <strong><%=@credit.points%>credits credit pack</strong></h2>
  <p> Your new balance is <%=number_to_currency(@order.user.credit_balance)%>
<%end%>
Click here to go back
<%= link_to "home", root_path %>

app/views/charges/new.html.erb
<%= form_tag credit_charges_path do %>
<article>
  <% if flash[:error].present? %>
  <div id="error_explanation">
    <p><%= flash[:error] %></p>
  </div>
  <% end %>
  <label class="amount">
    <span>Amount: $<%=@credit.price%></span>
  </label>
</article>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
data-description="Credit pack of $<%= @price%>"
data-amount=<%= @credit.price * 100 %>
data-email= "<%= current_user.email -%>"
data-locale="auto"></script>
<% end %>